"""
Initial schema.

Revision ID: b8e2d71fc4bf
Revises: 799e00d1e251
Create Date: 2025-10-09 03:22:36.390629

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "b8e2d71fc4bf"
down_revision: Union[str, Sequence[str], None] = "799e00d1e251"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
